### ISSUE TITLE
Is there a way to access the TX and RX of the SARA directly? 

### ISSUE THREAD

**Issue by michaelboeding** [sparkfun/MicroMod_Asset_Tracker#10]

**Comment by PaulZC** [comment]
Hi Michael (@michaelboeding ),

Apologies for the slow reply.

Yes, you can use the [firmware update tool](https://www.sparkfun.com/products/17725) to provide direct access to TX and RX. Either over USB, or - with some careful cutting and soldering - via [jumper pins](https://learn.sparkfun.com/tutorials/micromod-update-tool-hookup-guide/using-the-pth-connections) soldered onto the update tool.

Best wishes,
Paul
